# Generated by Django 3.2.5 on 2021-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailname', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
    ]
